// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tontine.WebAPI.Data;

#nullable disable

namespace tontine.WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423123109_AddPaiementMobile")]
    partial class AddPaiementMobile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("tontine.WebAPI.Models.CompteUtilisateurModel", b =>
                {
                    b.Property<int>("IdCompte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_compte");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCompte"));

                    b.Property<DateOnly>("DateCreation")
                        .HasColumnType("date")
                        .HasColumnName("date_creation");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("MotDePasse")
                        .HasColumnType("longtext")
                        .HasColumnName("mot_de_passe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nom");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext")
                        .HasColumnName("photo");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("prenom");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("statut");

                    b.HasKey("IdCompte");

                    b.ToTable("compte_utilisateur");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.CotisationModel", b =>
                {
                    b.Property<int>("IdCotisation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cotisation");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCotisation"));

                    b.Property<DateTime>("DateCotisation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_cotisation");

                    b.Property<int>("IdCycle")
                        .HasColumnType("int")
                        .HasColumnName("id_cycle");

                    b.Property<int>("IdMembre")
                        .HasColumnType("int")
                        .HasColumnName("id_membre");

                    b.Property<int>("IdTontine")
                        .HasColumnType("int")
                        .HasColumnName("id_tontine");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("montant");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("statut");

                    b.HasKey("IdCotisation");

                    b.HasIndex("IdCycle");

                    b.HasIndex("IdMembre");

                    b.HasIndex("IdTontine");

                    b.ToTable("cotisation");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.CycleModel", b =>
                {
                    b.Property<int>("IdCycle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cycle");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCycle"));

                    b.Property<DateOnly?>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<string>("NomCycle")
                        .HasColumnType("longtext")
                        .HasColumnName("nom_cycle");

                    b.Property<string>("Statut")
                        .HasColumnType("longtext")
                        .HasColumnName("statut");

                    b.HasKey("IdCycle");

                    b.ToTable("cycle");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.CycleTontineModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCycle")
                        .HasColumnType("int")
                        .HasColumnName("id_cycle");

                    b.Property<int>("IdTontine")
                        .HasColumnType("int")
                        .HasColumnName("id_tontine");

                    b.HasKey("Id");

                    b.HasIndex("IdCycle");

                    b.HasIndex("IdTontine");

                    b.ToTable("cycle_tontine");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.CycleTontinePenaliteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdCycle")
                        .HasColumnType("int")
                        .HasColumnName("id_cycle");

                    b.Property<int?>("IdPenalite")
                        .HasColumnType("int")
                        .HasColumnName("id_penalite");

                    b.Property<int?>("IdTontine")
                        .HasColumnType("int")
                        .HasColumnName("id_tontine");

                    b.Property<decimal?>("TauxApres")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("taux_apres");

                    b.Property<decimal?>("TauxAvant")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("taux_avant");

                    b.HasKey("Id");

                    b.HasIndex("IdCycle");

                    b.HasIndex("IdPenalite");

                    b.HasIndex("IdTontine");

                    b.ToTable("cycle_tontine_penalite");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.GarantModel", b =>
                {
                    b.Property<int>("IdGarant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_garant");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdGarant"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("adresse");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_ajout");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<int>("IdMembre")
                        .HasColumnType("int")
                        .HasColumnName("id_membre");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Relation")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("relation");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telephone");

                    b.HasKey("IdGarant");

                    b.ToTable("garant");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.HistoriqueMdpModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modification");

                    b.Property<int>("IdCompte")
                        .HasColumnType("int")
                        .HasColumnName("id_compte");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mot_de_passe");

                    b.HasKey("Id");

                    b.ToTable("historique_mdp");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.JournalActiviteModel", b =>
                {
                    b.Property<int>("IdJournal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_journal");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdJournal"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_action");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Utilisateur")
                        .HasColumnType("longtext")
                        .HasColumnName("utilisateur");

                    b.HasKey("IdJournal");

                    b.ToTable("journal_activite");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.MembreCycleTontineModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCycle")
                        .HasColumnType("int")
                        .HasColumnName("id_cycle");

                    b.Property<int>("IdMembre")
                        .HasColumnType("int")
                        .HasColumnName("id_membre");

                    b.Property<int>("IdTontine")
                        .HasColumnType("int")
                        .HasColumnName("id_tontine");

                    b.HasKey("Id");

                    b.HasIndex("IdCycle");

                    b.HasIndex("IdMembre");

                    b.HasIndex("IdTontine");

                    b.ToTable("membre_cycle_tontine");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.MembreModel", b =>
                {
                    b.Property<int>("IdMembre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_membre");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMembre"));

                    b.Property<string>("Adresse")
                        .HasColumnType("longtext")
                        .HasColumnName("adresse");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_inscription");

                    b.Property<DateOnly?>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("date_naissance");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nom");

                    b.Property<string>("NumeroCni")
                        .HasColumnType("longtext")
                        .HasColumnName("numero_cni");

                    b.Property<string>("Pays")
                        .HasColumnType("longtext")
                        .HasColumnName("pays");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext")
                        .HasColumnName("photo");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("prenom");

                    b.Property<string>("Profession")
                        .HasColumnType("longtext")
                        .HasColumnName("profession");

                    b.Property<string>("Sexe")
                        .HasColumnType("longtext")
                        .HasColumnName("sexe");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext")
                        .HasColumnName("telephone");

                    b.Property<string>("Ville")
                        .HasColumnType("longtext")
                        .HasColumnName("ville");

                    b.HasKey("IdMembre");

                    b.ToTable("membre");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.MembrePosteCycleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("longtext")
                        .HasColumnName("commentaire");

                    b.Property<int>("IdCycle")
                        .HasColumnType("int")
                        .HasColumnName("id_cycle");

                    b.Property<int>("IdMembre")
                        .HasColumnType("int")
                        .HasColumnName("id_membre");

                    b.Property<int>("IdPoste")
                        .HasColumnType("int")
                        .HasColumnName("id_poste");

                    b.Property<int>("IdTontine")
                        .HasColumnType("int")
                        .HasColumnName("id_tontine");

                    b.HasKey("Id");

                    b.HasIndex("IdCycle");

                    b.HasIndex("IdMembre");

                    b.HasIndex("IdPoste");

                    b.HasIndex("IdTontine");

                    b.ToTable("membre_poste_cycle");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.PaiementMobileModel", b =>
                {
                    b.Property<int>("IdPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_paiement");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPaiement"));

                    b.Property<DateTime?>("DateConfirmation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_confirmation");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation");

                    b.Property<int?>("IdCotisation")
                        .HasColumnType("int")
                        .HasColumnName("id_cotisation");

                    b.Property<string>("MessageErreur")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message_erreur");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("montant");

                    b.Property<string>("Operateur")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("operateur");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reference");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("statut");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdPaiement");

                    b.HasIndex("IdCotisation");

                    b.ToTable("paiement_mobile");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.PenaliteModel", b =>
                {
                    b.Property<int>("IdPenalite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_penalite");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPenalite"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Libelle")
                        .HasColumnType("longtext")
                        .HasColumnName("libelle");

                    b.HasKey("IdPenalite");

                    b.ToTable("penalite");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.PosteModel", b =>
                {
                    b.Property<int>("IdPoste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_poste");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPoste"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("LibellePoste")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("libelle_poste");

                    b.HasKey("IdPoste");

                    b.ToTable("poste");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.Pret", b =>
                {
                    b.Property<int>("IdPret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pret");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPret"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation");

                    b.Property<DateTime>("DatePret")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_pret");

                    b.Property<DateTime?>("DateRemboursement")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_remboursement");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("IdMembre")
                        .HasColumnType("int")
                        .HasColumnName("id_membre");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("montant");

                    b.Property<decimal>("MontantRemboursé")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("montant_rembourse");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("statut");

                    b.Property<decimal>("Taux")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("taux");

                    b.HasKey("IdPret");

                    b.ToTable("pret");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.TontineModel", b =>
                {
                    b.Property<int>("IdTontine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tontine");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTontine"));

                    b.Property<string>("Frequence")
                        .HasColumnType("longtext")
                        .HasColumnName("frequence");

                    b.Property<string>("Libelle")
                        .HasColumnType("longtext")
                        .HasColumnName("libelle");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("montant");

                    b.HasKey("IdTontine");

                    b.ToTable("tontine");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.VersementModel", b =>
                {
                    b.Property<int>("IdVersement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_versement");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVersement"));

                    b.Property<DateTime>("DateVersement")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_versement");

                    b.Property<int>("IdCycle")
                        .HasColumnType("int")
                        .HasColumnName("id_cycle");

                    b.Property<int>("IdMembre")
                        .HasColumnType("int")
                        .HasColumnName("id_membre");

                    b.Property<int>("IdTontine")
                        .HasColumnType("int")
                        .HasColumnName("id_tontine");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("montant");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.HasKey("IdVersement");

                    b.HasIndex("IdCycle");

                    b.HasIndex("IdMembre");

                    b.HasIndex("IdTontine");

                    b.ToTable("versement");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.CotisationModel", b =>
                {
                    b.HasOne("tontine.WebAPI.Models.CycleModel", "Cycle")
                        .WithMany()
                        .HasForeignKey("IdCycle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tontine.WebAPI.Models.MembreModel", "Membre")
                        .WithMany()
                        .HasForeignKey("IdMembre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tontine.WebAPI.Models.TontineModel", "Tontine")
                        .WithMany()
                        .HasForeignKey("IdTontine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Membre");

                    b.Navigation("Tontine");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.CycleTontineModel", b =>
                {
                    b.HasOne("tontine.WebAPI.Models.CycleModel", "Cycle")
                        .WithMany()
                        .HasForeignKey("IdCycle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tontine.WebAPI.Models.TontineModel", "Tontine")
                        .WithMany()
                        .HasForeignKey("IdTontine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Tontine");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.CycleTontinePenaliteModel", b =>
                {
                    b.HasOne("tontine.WebAPI.Models.CycleModel", "Cycle")
                        .WithMany()
                        .HasForeignKey("IdCycle");

                    b.HasOne("tontine.WebAPI.Models.PenaliteModel", "Penalite")
                        .WithMany()
                        .HasForeignKey("IdPenalite");

                    b.HasOne("tontine.WebAPI.Models.TontineModel", "Tontine")
                        .WithMany()
                        .HasForeignKey("IdTontine");

                    b.Navigation("Cycle");

                    b.Navigation("Penalite");

                    b.Navigation("Tontine");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.MembreCycleTontineModel", b =>
                {
                    b.HasOne("tontine.WebAPI.Models.CycleModel", "Cycle")
                        .WithMany()
                        .HasForeignKey("IdCycle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tontine.WebAPI.Models.MembreModel", "Membre")
                        .WithMany()
                        .HasForeignKey("IdMembre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tontine.WebAPI.Models.TontineModel", "Tontine")
                        .WithMany()
                        .HasForeignKey("IdTontine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Membre");

                    b.Navigation("Tontine");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.MembrePosteCycleModel", b =>
                {
                    b.HasOne("tontine.WebAPI.Models.CycleModel", "Cycle")
                        .WithMany()
                        .HasForeignKey("IdCycle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tontine.WebAPI.Models.MembreModel", "Membre")
                        .WithMany()
                        .HasForeignKey("IdMembre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tontine.WebAPI.Models.PosteModel", "Poste")
                        .WithMany()
                        .HasForeignKey("IdPoste")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tontine.WebAPI.Models.TontineModel", "Tontine")
                        .WithMany()
                        .HasForeignKey("IdTontine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Membre");

                    b.Navigation("Poste");

                    b.Navigation("Tontine");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.PaiementMobileModel", b =>
                {
                    b.HasOne("tontine.WebAPI.Models.CotisationModel", "Cotisation")
                        .WithMany()
                        .HasForeignKey("IdCotisation");

                    b.Navigation("Cotisation");
                });

            modelBuilder.Entity("tontine.WebAPI.Models.VersementModel", b =>
                {
                    b.HasOne("tontine.WebAPI.Models.CycleModel", "Cycle")
                        .WithMany()
                        .HasForeignKey("IdCycle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tontine.WebAPI.Models.MembreModel", "Membre")
                        .WithMany()
                        .HasForeignKey("IdMembre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tontine.WebAPI.Models.TontineModel", "Tontine")
                        .WithMany()
                        .HasForeignKey("IdTontine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Membre");

                    b.Navigation("Tontine");
                });
#pragma warning restore 612, 618
        }
    }
}
